version: '2.2'

services:
  claude_colissend_db:
    extends:
      file: common.prod.yml
      service: claude_colissend_db
    restart: always
    environment:
      MYSQL_DATABASE: colissend
      MYSQL_ROOT_PASSWORD: mariapwd

  claude_colissend_php-fpm:
    extends:
      file: common.prod.yml
      service: claude_colissend_php-fpm
    restart: always
    links:
      - claude_colissend_db
      - claude_colissend_redis
    networks:
      - proxy
      - colissend-net

  claude_colissend_nginx:
    extends:
      file: common.prod.yml
      service: claude_colissend_nginx
    restart: always
    labels:
      - traefik.http.routers.claude_colissend_nginx-secure.rule=Host(`${DOMAIN}`)
    depends_on:
      - claude_colissend_php-fpm
    build:
      args:
        development: 0
        nginxconf: nginx_dev_claude.conf

  claude_colissend_redis:
    extends:
      file: common.prod.yml
      service: claude_colissend_redis
    expose:
      - 6379
    restart: always

networks:
  colissend-net:
    external: true
  proxy:
    external: true
  database-net:
    external: true